version: "3.8"

services:
  mongo:
    image: mongo:8.2
    container_name: almaspot-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}

  unibo-provider:
    build:
      context: ./unibo-provider
      dockerfile: Dockerfile
    container_name: almaspot-unibo-provider
    ports:
      - "8080:8080"
    networks:
      - almaspot-network
    restart: unless-stopped

networks:
  almaspot-network:
    driver: bridge

volumes:
  mongo_data:
