services:
  mongo:
    image: mongo:8.3
    container_name: almaspot-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    networks:
      - almaspot-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: ./server
    container_name: almaspot-server
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DB_NAME}?authSource=admin
      - PORT=${PORT}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_SUBJECT=${VAPID_SUBJECT}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - UNIBO_SERVICE_URL=${UNIBO_SERVICE_URL}
      - NODE_ENV=development
      - HOST=0.0.0.0
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}

    command: npm run dev

    volumes:
      - ./server:/app
      - /app/node_modules

    networks:
      - almaspot-network

    depends_on:
      mongo:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${PORT}/health"]
      interval: 20s
      timeout: 10s
      retries: 20
      start_period: 10s

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: almaspot-client
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:${PORT}
      - VITE_VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
    networks:
      - almaspot-network
    depends_on:
      server:
        condition: service_healthy

  unibo-provider:
    build:
      context: unibo-provider
      dockerfile: Dockerfile
    container_name: almaspot-unibo-provider
    ports:
      - "8080:8080"
    networks:
      - almaspot-network
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - almaspot-network

networks:
  almaspot-network:
    driver: bridge

volumes:
  mongo_data:
