name: PR checks

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 24.x

jobs:
  test-and-build:
    name: Style, Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${{ env.NODE_VERSION }}"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint --if-present

      - name: Run Tests
        run: npm test --if-present

      - name: Build Project
        run: npm run build --if-present

  commit-check:
    name: Validate Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${{ env.NODE_VERSION }}"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Validate commit messages
        run: |
          npx commitlint \
            --config commitlint.config.js \
            --from ${{ github.event.pull_request.base.sha }} \
            --to ${{ github.event.pull_request.head.sha }} \
            --verbose

  success:
    needs:
      - test-and-build
      - commit-check
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Verify there are no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}
